### ISSUE TITLE
Huff Review for Dotson ANS Summary

### ISSUE THREAD

**Issue by samgdotson** [arfc/2019-dotson-inception-ans#1]
[dotson-inn-ans.pdf](https://github.com/arfc/dotson-inception-ans/files/3347594/dotson-inn-ans.pdf)

**Comment by katyhuff** [comment]
Completed. 
I will open a new issue that you can close by addressing the comments.

@mitchellwhalen thanks for doing the first round of edits. I did notice a couple of things that fell through the cracks (in green), so maybe consider being extra aware of some of those particular items next time, if you can.

[2019-dotson-inception.pdf](https://github.com/arfc/dotson-inception-ans/files/3350478/2019-dotson-inception.pdf)
