### ISSUE TITLE
Address Huff Comments

### ISSUE THREAD

**Issue by katyhuff** [arfc/2019-dotson-inception-ans#3]
My review is here. This issue can be closed when the items noted in the pdf are corrected or handled. 

[2019-dotson-inception.pdf](https://github.com/arfc/dotson-inception-ans/files/3350478/2019-dotson-inception.pdf)

A few overarching notes:

- [x] All variables should be defined clearly, with units. My preference is a style like this, for each equation:

```tex
\begin{align}
A &= \lambda N\\
A &= \mbox{total activity } [s^{-1}]\\
\lambda &= \mbox{decay constant, reciprocal of the mean lifetime } [s^{-1}]\\
N &= \mbox{total number of particles in the sample } [-]
\end{align}
```

- [x] Cite all software
- [x] I prefer Figure and Table over "figure" and "table"
- [x] I know you know this... there is something funky about your citations. Some are (Authorname, Year) while others are (correctly) [1].
- [x] It will help to have a table indicating the training parameters you intend to explore.
- [x] A few sentences would be clearer if they were active voice. 

Also, please review the writing checklist:

- [x] Run a spell checker.
- [x] The Oxford comma appears in  ("lions, tigers, and bears.")
- [x] Do not use the word "where" unless referring to a location (try "such that" or "in which").
- [x] Articles such as "a" "the" "some" "any" and "each" appear where necessary.
- [x] All subjects match the plurality of their verbs ( no: "Apples is tasty" yes: "Apples are tasty")
- [ ] Avoid run-on sentences.
- [x] clunky nouns -> spunky verbs (progression, expression --> progress, express)
- [x] reduce vague words (important, methodologic)
- [x] reduce acronyms / jargon
- [ ] get rid of unnecessary prepositional phrases -- author clearing throat (It can be shown that)
- [x] get rid of extraneous adverbs (very, really, quite, basically, generally)
- [x] get rid of there are / there is
- [x] turn negatives to positives (she was not often right -> she was usually wrong)
- [x] get rid of extraneous prepositions (the meeting happened on monday -> the meeting happened monday) (they agreed that it was true -> they agreed it was true)
- [ ] get rid of passive voice (is/was/are/were/be/been/am + past tense verb), replace with active voice
- [x] use strong verbs (use sparingly: is, are, was, were, be, been, am)
- [ ] avoid turning verbs into nouns ("obtain estimates of" -> "estimates"; "provides a description of" -> "describes") 
- [x] don't bury the verb (keep the predicate close to the subject at the beginning of the sentence)
- [x] data is plural (the data are critical)
- [ ] compare to (point out similarities between different things) vs.  compared with (point out differences between similar things)
- [x] punctuation helps you to vary your sentence structure
- [x] Power to separate in increasing power: comma, colon, dash, parentheses, semicolon, period
- [x] In increasing order of formality: dash, parentheses, all of the others. Don't overdo it with the dash and parentheses
- [x] semicolon: connects two independent clauses. OR used to separate when the items in the list contain internal punctuation.
- [x] use a colon to introduce a list, quote, explanation, conclusion, or amplification
- [x] if there's a list in a sentence, it shouldn't come before the colon
- [x] use a dash to insert something in the middle of the sentence. Don't overuse it.

**Comment by samgdotson** [comment]
I _believe_ I have completed most of the checkpoints on this list and certain I have addressed your overarching notes. The paragraph underlined in blue, _Network Structure and Hyperparameters_ I don't think is paraphrased from anywhere. I checked Mark's papers, but much of the content is specific to inception networks. Overlap is due to general statements about neural networks. To be safe, I added a citation for Mark's most recent paper that included a table of hyperparameters.

[2019-dotson-inn-ans.pdf](https://github.com/arfc/2019-dotson-inception-ans/files/3352422/dotson-inn-ans.pdf)

**Comment by katyhuff** [comment]
Thanks. I like the look of the final pdf, but I 'm concerned that there is a proliferation of documents in the repository. Let's chat a bit tomorrow about the purpose of version control in this kind of application. There is no need to create new folders with new drafts. The purpose of using version control is to allow there to be only one current version of each file, with all past drafts saved in the commit history.

Additionally, please don't add documents that are computer generated, if possible. Only add source files to the repository, not built files. Please review the chapters in Effective Computation In Physics regarding local and remote version control.

I will make a few edits in a separate PR, then you can submit to ANS.
